"use strict";
exports.APP_MESSAGES = {
  SUCCESS: "Successful",
  SERVER_ERROR: "Something went wrong. Please try again later",
  FAILED: "Failed",
  FOLLOW_SUCCESS:"Followed",
  UNFOLLOW_SUCCESS:"Unfollowed",
  SUBSCRIBE_SUCCESS:"Subscribed",
  UNSUBSCRIBE_SUCCESS:"Unsubscribed",
  INVALID_FILE:"Not a CSV File!",
  SUBSCRIBE_SUCCESS: "Subscribed",
  UNSUBSCRIBE_SUCCESS: "Unsubscribed",
  SIGNUP_SUCCESS: "Registered successfully",
  INVALID_CREDENTAILS: "Invalid Credentials",
  USER_EXIST: "User already exists",
  SIGNUP_FAILED: "the user cannot be created!",
  EMAIL_NOT_REGISTERED: "Please check the email address and try again",
  PHONE_NOT_REGISTERED: "Please check the phone number and try again",
  INCORECT_PASSWORD: "Password does not match, Please try again",
  LOGIN_SUCCESS: "Login successful",
  INVALID_TOKEN: "Invalid token",
  AUTH_TOKEN_MISSING: "Auth token is missing",
  PASSWORD_CHANGE_SUCCESS: "Password changed successfully",
};
